
--------------------------------------------------------
--  DDL for Table BASKET
--------------------------------------------------------

  CREATE TABLE "ZHAN"."BASKET" 
   (	"ARTISTS_ID" NUMBER(11,0), 
	"ARTS_ID" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Ref Constraints for Table BASKET
--------------------------------------------------------

  ALTER TABLE "ZHAN"."BASKET" ADD CONSTRAINT "FK_ARTS" FOREIGN KEY ("ARTS_ID")
	  REFERENCES "ZHAN"."ARTS" ("ARTS_ID") ENABLE;
 
  ALTER TABLE "ZHAN"."BASKET" ADD CONSTRAINT "FK_ARTSTS" FOREIGN KEY ("ARTISTS_ID")
	  REFERENCES "ZHAN"."ARTISTS" ("ARTISTS_ID") ENABLE;
